### ISSUE TITLE
Tempo

### ISSUE THREAD

**Issue by wagner-lucas** [alessonrenato/petrijobs#3]
Amigos como vamos fazer para pegar a hora atual do sistema?.

**Comment by iWarhead** [comment]
Talvez possamos usar a constante __TIME__ que pega a hora atual do sistema. O que acham?

**Comment by wagner-lucas** [comment]
Pode ser arthur, mas como funciona essa constante?

**Comment by wagner-lucas** [comment]
Ja sei como recolher o tempo, vou usar a função alarme.
